/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/carpets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Carpets
         * @description The management table's own listing — inactive carpets included.
         *
         *     `is_active` defaults to None meaning «both», which is the whole point: the
         *     shop's listing hides deactivated carpets, so without this the only way back
         *     to one would be to remember its id.
         */
        get: operations["list_admin_carpets_api_v1_admin_carpets_get"];
        put?: never;
        /** Create Carpet */
        post: operations["create_carpet_api_v1_admin_carpets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/carpets/{carpet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Carpet
         * @description One carpet for the edit screen — by id, and without the active filter.
         *
         *     The shop's own `/carpets/{slug}` cannot serve this. It looks up by slug and
         *     requires `is_active`, so the moment a carpet is deactivated the panel could
         *     no longer open the page that would turn it back on. By id, because the slug
         *     is one of the things being edited.
         */
        get: operations["get_admin_carpet_api_v1_admin_carpets__carpet_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Carpet */
        patch: operations["update_carpet_api_v1_admin_carpets__carpet_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/carpets/{carpet_id}/ar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ar Status */
        get: operations["ar_status_api_v1_admin_carpets__carpet_id__ar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/carpets/{carpet_id}/ar/corners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest Corners
         * @description گوشه‌هایی که فایل‌های فعلی با آن ساخته شده‌اند، کنار تشخیص خودکار.
         */
        get: operations["suggest_corners_api_v1_admin_carpets__carpet_id__ar_corners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/carpets/{carpet_id}/ar/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Ar Assets
         * @description ساخت (یا بازسازی) فایل‌های AR برای همه‌ی سایزهای این فرش.
         */
        post: operations["generate_ar_assets_api_v1_admin_carpets__carpet_id__ar_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/carpets/{carpet_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image
         * @description آپلود عکس: مشتقات WebP ساخته می‌شود، امبدینگ محاسبه و ذخیره می‌شود.
         */
        post: operations["upload_image_api_v1_admin_carpets__carpet_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/carpets/{carpet_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Variant */
        post: operations["add_variant_api_v1_admin_carpets__carpet_id__variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Image */
        delete: operations["delete_image_api_v1_admin_images__image_id__delete"];
        options?: never;
        head?: never;
        /** Update Image */
        patch: operations["update_image_api_v1_admin_images__image_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_admin_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Order Status */
        patch: operations["update_order_status_api_v1_admin_orders__order_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description Counters for the dashboard, counted in the database.
         */
        get: operations["stats_api_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Variant */
        delete: operations["delete_variant_api_v1_admin_variants__variant_id__delete"];
        options?: never;
        head?: never;
        /** Update Variant */
        patch: operations["update_variant_api_v1_admin_variants__variant_id__patch"];
        trace?: never;
    };
    "/api/v1/carpets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Carpets */
        get: operations["list_carpets_api_v1_carpets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carpets/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog Facets
         * @description شمارش هر فیلتر و توزیع قیمت — ورودی پنل فیلتر.
         *
         *     پیش از `/{slug}` تعریف شده، وگرنه «facets» به‌عنوان اسلاگ یک فرش خوانده
         *     می‌شود و همیشه ۴۰۴ می‌دهد.
         */
        get: operations["catalog_facets_api_v1_carpets_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carpets/{carpet_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Similar Carpets
         * @description فرش‌های مشابه برای صفحه‌ی محصول — با امبدینگ عکس اصلی همان فرش.
         */
        get: operations["similar_carpets_api_v1_carpets__carpet_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carpets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carpet Detail */
        get: operations["carpet_detail_api_v1_carpets__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Order
         * @description ثبت سفارش مهمان. پرداخت شبیه‌سازی‌شده است و سفارش «در انتظار تأیید» می‌ماند.
         */
        post: operations["create_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track Order
         * @description پیگیری با کد رهگیری + شماره‌ی موبایل (هر دو باید بخوانند تا اطلاعات لو نرود).
         */
        post: operations["track_order_api_v1_orders_track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/adviser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Room Adviser
         * @description عکس اتاق → فرش‌هایی که به آن می‌آیند، با دلیل هر کدام.
         *
         *     Shares its first half with the size guide — the same depth, the same floor
         *     mask — and then asks a different question of it. That one measures the floor
         *     and answers «چه اندازه‌ای»; this one reads the colours on either side of the
         *     same mask and answers «کدام فرش». Both are deliberately separate endpoints:
         *     a shopper who wants a size does not want to wait for a ranking, and the two
         *     answers belong on different pages.
         */
        post: operations["room_adviser_api_v1_room_adviser_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/room/size-guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Size Guide
         * @description عکس اتاق → اندازه‌های فرشی که در فضای آزاد جا می‌شوند.
         */
        post: operations["size_guide_api_v1_room_size_guide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/conversational": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conversational Search
         * @description جمله‌ی فارسی → فیلتر ساخت‌یافته → همان نتایجی که کاتالوگ می‌دهد.
         *
         *     The sentence is translated, never answered. Whatever the planner produces is
         *     a `CatalogFilters` like any other, run through the same `list_carpets` the
         *     listing page calls — so this endpoint cannot return a carpet the catalogue
         *     would not, at a price it does not charge, however the translation went.
         */
        post: operations["conversational_search_api_v1_search_conversational_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/visual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Visual Search
         * @description عکس فرش (یا اتاق) → شبیه‌ترین فرش‌های کاتالوگ.
         */
        post: operations["visual_search_api_v1_search_visual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminCarpetDetail
         * @description A carpet as the edit screen needs it: everything the shop sees, plus
         *     whether the shop is allowed to see it.
         *
         *     `is_active` is absent from the public shape for a good reason — the
         *     storefront only ever receives active carpets, so the field would be a
         *     constant `true` on every response and mean nothing. Here it is the state a
         *     whole button exists to change.
         */
        AdminCarpetDetail: {
            /** Color Families */
            color_families: components["schemas"]["ColorFamily"][];
            /** Colors */
            colors: string[];
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Images */
            images: components["schemas"]["ImageOut"][];
            /** Is Active */
            is_active: boolean;
            material: components["schemas"]["CarpetMaterial"];
            /** Name */
            name: string;
            /** Origin */
            origin: string | null;
            pattern: components["schemas"]["CarpetPattern"];
            /** Slug */
            slug: string;
            /** Suitable Rooms */
            suitable_rooms: components["schemas"]["RoomType"][];
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
        };
        /**
         * AdminCarpetRow
         * @description One row of the carpet management table (ROADMAP §6-15).
         *
         *     Deliberately not `CarpetListItem`. That one is the shop's view and hides
         *     everything a shopper must not see — above all it only ever returns active
         *     carpets, so an admin who deactivated a carpet could never find it again to
         *     turn it back on.
         */
        AdminCarpetRow: {
            /** Ar Ready */
            ar_ready: number;
            /** Id */
            id: number;
            /** Images Count */
            images_count: number;
            /** Is Active */
            is_active: boolean;
            material: components["schemas"]["CarpetMaterial"];
            /** Max Price */
            max_price: string | null;
            /** Min Price */
            min_price: string | null;
            /** Name */
            name: string;
            /** Origin */
            origin: string | null;
            pattern: components["schemas"]["CarpetPattern"];
            /** Primary Image */
            primary_image: string | null;
            /** Slug */
            slug: string;
            /** Variants Count */
            variants_count: number;
        };
        /**
         * AdminOrderItemOut
         * @description A line of an order, with enough of the carpet to recognise and open it.
         *
         *     A subclass rather than three more fields on `OrderItemOut`, for the reason
         *     the panel's other shapes are also subclasses: the public line is what a
         *     buyer is shown when they track a parcel, and it should carry the name and
         *     the size they bought and nothing else. None of this is secret — it is the
         *     catalogue — it is simply not part of the answer to «where is my order».
         *
         *     Every one of them is optional, and that is the data model rather than
         *     caution. `OrderItem.variant_id` is `ON DELETE SET NULL` on purpose, so that
         *     removing a size a shop no longer sells leaves the orders that bought it
         *     readable; the line keeps its own copy of the name, the size and the price.
         *     What it cannot keep is the way back to the carpet. So a line whose size has
         *     since been deleted arrives with the text and no picture, which is exactly
         *     what is true about it.
         */
        AdminOrderItemOut: {
            /** Carpet Id */
            carpet_id?: number | null;
            /** Carpet Image */
            carpet_image?: string | null;
            /** Carpet Name */
            carpet_name: string;
            /** Length Cm */
            length_cm: number;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Variant Id */
            variant_id?: number | null;
            /** Width Cm */
            width_cm: number;
        };
        /**
         * AdminOrderOut
         * @description An order as the shopkeeper needs to see it (ROADMAP §6-17).
         *
         *     Separate from the public `OrderOut` in both directions.
         *
         *     It carries **more**: the phone number and address, without which an order
         *     cannot be fulfilled, and `created_at`, without which a list of orders has
         *     no order. And `id` — the status endpoint is keyed by id, so a management
         *     table built on the public shape could list orders and never change one.
         *
         *     It also leaves the public shape **alone**, which is the point. Someone
         *     tracking a parcel proves who they are with a reference and a phone number;
         *     echoing the delivery address back into that response would put it one
         *     guessed reference away from a stranger.
         */
        AdminOrderOut: {
            /** Address */
            address: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Name */
            customer_name: string;
            /** Customer Phone */
            customer_phone: string;
            /** Id */
            id: number;
            /** Items */
            items: components["schemas"]["AdminOrderItemOut"][];
            /** Note */
            note: string | null;
            /** Reference */
            reference: string;
            status: components["schemas"]["OrderStatus"];
            /** Total */
            total: string;
        };
        /**
         * AdminStats
         * @description The dashboard's counters (ROADMAP §6-14).
         *
         *     Counted in the database rather than by measuring the length of a list the
         *     API returned. `/admin/orders` caps at 200 rows, so counting its response
         *     would quietly stop being true on the two-hundred-and-first order — and a
         *     dashboard that is wrong only once the shop gets busy is worse than none.
         */
        AdminStats: {
            /** Ar Failed */
            ar_failed: number;
            /** Ar Missing */
            ar_missing: number;
            /** Ar Processing */
            ar_processing: number;
            /** Ar Ready */
            ar_ready: number;
            /** Carpets Active */
            carpets_active: number;
            /** Carpets Inactive */
            carpets_inactive: number;
            /** Confirmed Total */
            confirmed_total: string;
            /** Orders Cancelled */
            orders_cancelled: number;
            /** Orders Confirmed */
            orders_confirmed: number;
            /** Orders Pending */
            orders_pending: number;
            /** Variants Total */
            variants_total: number;
        };
        /**
         * ArAssetStatus
         * @description Lifecycle of the automatically generated AR files for a variant.
         * @enum {string}
         */
        ArAssetStatus: "missing" | "processing" | "ready" | "failed";
        /**
         * ArCornerSuggestion
         * @description Where the corner editor should open, and where automatic detection is.
         *
         *     Two sets, because the screen needs both. `corners` is what the handles are
         *     placed on: the crop the AR files on disk were built from, if any have been
         *     built, and detection otherwise. `detected` is always what detection says
         *     right now, which is what «بازگرداندن گوشه‌های تشخیص‌داده‌شده» puts back —
         *     a button that could not exist while the two were the same field.
         */
        ArCornerSuggestion: {
            /** Confidence */
            confidence: number;
            /** Corners */
            corners: components["schemas"]["CornerPoint"][];
            /** Detected */
            detected: components["schemas"]["CornerPoint"][];
            /** Image Height */
            image_height: number;
            /** Image Width */
            image_width: number;
            /** Needs Review */
            needs_review: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "automatic" | "detected";
        };
        /**
         * ArGenerateRequest
         * @description Optional manual corners from the admin panel's draggable handles.
         *
         *     Order is top-left, top-right, bottom-right, bottom-left, in pixels of the
         *     original photo. Omit to let detection choose.
         */
        ArGenerateRequest: {
            /** Corners */
            corners?: components["schemas"]["CornerPoint"][] | null;
        };
        /** ArVariantStatus */
        ArVariantStatus: {
            /** Ar Error */
            ar_error: string | null;
            /** Ar Status */
            ar_status: string;
            /** Glb Url */
            glb_url: string | null;
            /** Length Cm */
            length_cm: number;
            /** Usdz Url */
            usdz_url: string | null;
            /** Variant Id */
            variant_id: number;
            /** Width Cm */
            width_cm: number;
        };
        /** Body_room_adviser_api_v1_room_adviser_post */
        Body_room_adviser_api_v1_room_adviser_post: {
            /** Image */
            image: string;
        };
        /** Body_size_guide_api_v1_room_size_guide_post */
        Body_size_guide_api_v1_room_size_guide_post: {
            /** Image */
            image: string;
        };
        /** Body_upload_image_api_v1_admin_carpets__carpet_id__images_post */
        Body_upload_image_api_v1_admin_carpets__carpet_id__images_post: {
            /** File */
            file: string;
        };
        /** Body_visual_search_api_v1_search_visual_post */
        Body_visual_search_api_v1_search_visual_post: {
            /** Image */
            image: string;
        };
        /** CarpetAdvice */
        CarpetAdvice: {
            carpet: components["schemas"]["CarpetListItem"];
            /**
             * Caution
             * @description اگر نکته‌ای هست که خریدار باید بداند، جدا از دلایل
             */
            caution?: string | null;
            /**
             * Reasons
             * @description چرا این فرش به این اتاق می‌آید، هر قاعده یک جمله
             */
            reasons?: string[];
            /**
             * Score
             * @description مجموع امتیاز قواعد؛ فقط برای مرتب‌سازی معنا دارد
             */
            score: number;
        };
        /** CarpetCreate */
        CarpetCreate: {
            /** Colors */
            colors?: string[];
            /** Description */
            description?: string | null;
            material: components["schemas"]["CarpetMaterial"];
            /** Name */
            name: string;
            /** Origin */
            origin?: string | null;
            pattern: components["schemas"]["CarpetPattern"];
            /** Slug */
            slug: string;
            /** Suitable Rooms */
            suitable_rooms?: components["schemas"]["RoomType"][];
        };
        /** CarpetDetail */
        CarpetDetail: {
            /** Color Families */
            color_families: components["schemas"]["ColorFamily"][];
            /** Colors */
            colors: string[];
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Images */
            images: components["schemas"]["ImageOut"][];
            material: components["schemas"]["CarpetMaterial"];
            /** Name */
            name: string;
            /** Origin */
            origin: string | null;
            pattern: components["schemas"]["CarpetPattern"];
            /** Slug */
            slug: string;
            /** Suitable Rooms */
            suitable_rooms: components["schemas"]["RoomType"][];
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
        };
        /** CarpetListItem */
        CarpetListItem: {
            /** Color Families */
            color_families: components["schemas"]["ColorFamily"][];
            /** Colors */
            colors: string[];
            /** Cover Image */
            cover_image?: string | null;
            /** Id */
            id: number;
            material: components["schemas"]["CarpetMaterial"];
            /** Min Price */
            min_price?: string | null;
            /** Name */
            name: string;
            pattern: components["schemas"]["CarpetPattern"];
            /** Primary Image */
            primary_image?: string | null;
            /**
             * Sizes Count
             * @default 0
             */
            sizes_count: number;
            /** Slug */
            slug: string;
        };
        /**
         * CarpetMaterial
         * @enum {string}
         */
        CarpetMaterial: "wool" | "silk" | "cotton" | "acrylic" | "polyester" | "viscose" | "mixed";
        /**
         * CarpetPattern
         * @enum {string}
         */
        CarpetPattern: "lachak_toranj" | "afshan" | "medallion" | "geometric" | "tribal" | "floral" | "modern" | "vintage" | "plain";
        /** CarpetUpdate */
        CarpetUpdate: {
            /** Colors */
            colors?: string[] | null;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            material?: components["schemas"]["CarpetMaterial"] | null;
            /** Name */
            name?: string | null;
            /** Origin */
            origin?: string | null;
            pattern?: components["schemas"]["CarpetPattern"] | null;
            /** Suitable Rooms */
            suitable_rooms?: components["schemas"]["RoomType"][] | null;
        };
        /**
         * CatalogFacets
         * @description Counts and ranges the filter panel needs before any filter is applied.
         *
         *     Keys are the enum *values* the API speaks (`silk`, `lachak_toranj`), so the
         *     storefront can look a count up by the same string it puts in the query.
         *     Members with no stock are simply absent rather than present with a zero.
         */
        CatalogFacets: {
            /** Colors */
            colors: {
                [key: string]: number;
            };
            /** Materials */
            materials: {
                [key: string]: number;
            };
            /** Max Price */
            max_price: string | null;
            /** Min Price */
            min_price: string | null;
            /** Patterns */
            patterns: {
                [key: string]: number;
            };
            /**
             * Price Histogram
             * @description ۳۲ سطل هم‌عرض بین min_price و max_price؛ تعداد سایزهای فروشی در هر سطل
             */
            price_histogram?: number[];
            /** Rooms */
            rooms: {
                [key: string]: number;
            };
        };
        /**
         * ColorFamily
         * @description The colours a shopper would name, as opposed to the ones a photo holds.
         *
         *     Dominant colours are stored as exact hex and are therefore nearly unique —
         *     useless as a filter. These are the buckets those hexes fall into, assigned
         *     in `app.services.color`, and the vocabulary is chosen for carpets rather
         *     than for colour theory: CREAM and TURQUOISE earn their place because Persian
         *     carpets are full of both and neither survives being called "pale yellow" or
         *     "cyan", while colours no carpet ground is woven in are simply absent.
         * @enum {string}
         */
        ColorFamily: "red" | "pink" | "orange" | "gold" | "cream" | "brown" | "green" | "turquoise" | "blue" | "purple" | "gray" | "black" | "white";
        /** ConversationalQuery */
        ConversationalQuery: {
            /**
             * Q
             * @description جمله‌ی فارسی کاربر
             */
            q: string;
        };
        /**
         * ConversationalSearchResponse
         * @description What the sentence was understood to mean, and what the shop answered.
         *
         *     The filters come back beside the results on purpose. A search that silently
         *     narrowed to four colour families has made a decision the visitor cannot
         *     argue with; returning it lets the interface show each decision as a chip
         *     they can drop, and lets «همه‌ی نتایج» be a real link into the ordinary
         *     catalogue rather than a second, parallel view of it.
         */
        ConversationalSearchResponse: {
            /**
             * Filters
             * @description فیلترهای استخراج‌شده، به شکل پارامترهای همان اندپوینت لیست
             */
            filters?: {
                [key: string]: unknown;
            };
            page: components["schemas"]["Page_CarpetListItem_"];
            /**
             * Understood
             * @description هر تصمیم جست‌وجو، به فارسی، برای بازبینی کاربر
             */
            understood?: string[];
        };
        /** CornerPoint */
        CornerPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageOut */
        ImageOut: {
            /** Full Url */
            full_url?: string | null;
            /** Id */
            id: number;
            /** Is Primary */
            is_primary: boolean;
            /** Position */
            position: number;
            /** Thumb Url */
            thumb_url?: string | null;
            /** Url */
            url: string;
        };
        /** ImageUpdate */
        ImageUpdate: {
            /** Is Primary */
            is_primary?: boolean | null;
            /** Position */
            position?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** OrderCreate */
        OrderCreate: {
            /** Address */
            address: string;
            /** Customer Name */
            customer_name: string;
            /** Customer Phone */
            customer_phone: string;
            /** Items */
            items: components["schemas"]["OrderItemIn"][];
            /** Note */
            note?: string | null;
        };
        /** OrderItemIn */
        OrderItemIn: {
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Variant Id */
            variant_id: number;
        };
        /** OrderItemOut */
        OrderItemOut: {
            /** Carpet Name */
            carpet_name: string;
            /** Length Cm */
            length_cm: number;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Width Cm */
            width_cm: number;
        };
        /** OrderOut */
        OrderOut: {
            /** Customer Name */
            customer_name: string;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /** Reference */
            reference: string;
            status: components["schemas"]["OrderStatus"];
            /** Total */
            total: string;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "pending" | "confirmed" | "cancelled";
        /** OrderStatusUpdate */
        OrderStatusUpdate: {
            status: components["schemas"]["OrderStatus"];
        };
        /** OrderTrackRequest */
        OrderTrackRequest: {
            /** Customer Phone */
            customer_phone: string;
            /** Reference */
            reference: string;
        };
        /** Page[AdminCarpetRow] */
        Page_AdminCarpetRow_: {
            /** Items */
            items: components["schemas"]["AdminCarpetRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[CarpetListItem] */
        Page_CarpetListItem_: {
            /** Items */
            items: components["schemas"]["CarpetListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * RoomAdviserResponse
         * @description One room photo, and the carpets that suit it with the reason for each.
         */
        RoomAdviserResponse: {
            /**
             * Confidence
             * @description ۰ تا ۱؛ اطمینان تشخیص کف. زیر ۰٫۴ یعنی خواندنِ رنگ‌ها هم مطمئن نیست
             */
            confidence: number;
            reading: components["schemas"]["RoomReading"];
            /** Suggestions */
            suggestions?: components["schemas"]["CarpetAdvice"][];
        };
        /**
         * RoomReading
         * @description What the photograph said about the room, before any carpet is proposed.
         *
         *     Returned to the shopper rather than kept behind the ranking, because the
         *     advice below rests on it: somebody who disagrees with «اتاق شما کم‌رنگ است»
         *     should be able to see that premise and stop reading, instead of wondering
         *     why the shop keeps offering them red.
         */
        RoomReading: {
            /**
             * Colourfulness
             * @description ۰ تا ۱؛ چقدر از اتاق رنگِ نام‌بردنی دارد
             */
            colourfulness: number;
            /**
             * Floor Colors
             * @description رنگ‌های غالب کفِ فعلی اتاق
             */
            floor_colors?: components["schemas"]["ColorFamily"][];
            /**
             * Lightness
             * @description ۰ تا ۱؛ روشنایی کلی اتاق بدون کف
             */
            lightness: number;
            /**
             * Room Colors
             * @description رنگ‌های غالب دیوارها و مبلمان
             */
            room_colors?: components["schemas"]["ColorFamily"][];
            /**
             * Warmth
             * @description warm | cool | neutral
             */
            warmth: string;
        };
        /**
         * RoomType
         * @enum {string}
         */
        RoomType: "living_room" | "bedroom" | "dining_room" | "kids_room" | "office" | "hallway";
        /**
         * ScaleReferenceOut
         * @description What the A4 sheet in the photo said about its scale.
         */
        ScaleReferenceOut: {
            /**
             * Correction Percent
             * @description درصد اصلاحی که برگه‌ی A4 روی تخمین عمق اعمال کرد؛ منفی یعنی مدل اتاق را بزرگ‌تر دیده بود
             */
            correction_percent: number;
            /**
             * Measured Long Cm
             * @description طول اندازه‌گیری‌شده‌ی برگه پیش از اصلاح
             */
            measured_long_cm: number;
        };
        /** SimilarItem */
        SimilarItem: {
            carpet: components["schemas"]["CarpetListItem"];
            /**
             * Similarity
             * @description ۱ = عین هم. ترکیب وزنی شباهت ساختار (امبدینگ) و شباهت رنگ (هیستوگرام HSV)؛ وقتی تصویر پرس‌وجو یا کاندید هیستوگرام نداشته باشد، فقط ساختار.
             */
            similarity: number;
        };
        /**
         * SizeGuideResponse
         * @description What one room photo says about the carpet it can take.
         */
        SizeGuideResponse: {
            /**
             * Camera Height M
             * @description ارتفاع بازیابی‌شده‌ی دوربین از کف
             */
            camera_height_m: number;
            /**
             * Confidence
             * @description ۰ تا ۱؛ اطمینان تشخیص کف. زیر ۰٫۴ یعنی عدد‌ها را با احتیاط بخوانید
             */
            confidence: number;
            /**
             * Free Area Sqm
             * @description مساحت کل کفِ در دسترس، نه فقط آن مستطیل
             */
            free_area_sqm: number;
            /**
             * Free Length Cm
             * @description طول همان محدوده
             */
            free_length_cm: number;
            /**
             * Free Width Cm
             * @description عرض بزرگ‌ترین محدوده‌ی آزادِ فرش‌شکل
             */
            free_width_cm: number;
            /**
             * Recommended
             * @description بزرگ‌ترین اندازه‌های موجود که در این محدوده جا می‌شوند، حداکثر شش تا
             */
            recommended?: components["schemas"]["SizeSuggestion"][];
            scale_reference?: components["schemas"]["ScaleReferenceOut"] | null;
        };
        /** SizeSuggestion */
        SizeSuggestion: {
            /**
             * Carpet Count
             * @description تعداد فرش‌های موجود در این اندازه
             */
            carpet_count: number;
            /** Length Cm */
            length_cm: number;
            /** Width Cm */
            width_cm: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariantCreate */
        VariantCreate: {
            /** Length Cm */
            length_cm: number;
            /** Price */
            price: number | string;
            /**
             * Stock
             * @default 0
             */
            stock: number;
            /** Width Cm */
            width_cm: number;
        };
        /** VariantOut */
        VariantOut: {
            ar_status: components["schemas"]["ArAssetStatus"];
            /** Glb Url */
            glb_url: string | null;
            /** Id */
            id: number;
            /** Length Cm */
            length_cm: number;
            /** Price */
            price: string;
            /** Stock */
            stock: number;
            /** Usdz Url */
            usdz_url: string | null;
            /** Width Cm */
            width_cm: number;
        };
        /** VariantUpdate */
        VariantUpdate: {
            /** Price */
            price?: number | string | null;
            /** Stock */
            stock?: number | null;
        };
        /** VisualSearchResponse */
        VisualSearchResponse: {
            /** Results */
            results: components["schemas"]["SimilarItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_admin_carpets_api_v1_admin_carpets_get: {
        parameters: {
            query?: {
                q?: string | null;
                is_active?: boolean | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminCarpetRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_carpet_api_v1_admin_carpets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarpetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarpetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_carpet_api_v1_admin_carpets__carpet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCarpetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_carpet_api_v1_admin_carpets__carpet_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarpetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarpetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ar_status_api_v1_admin_carpets__carpet_id__ar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArVariantStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_corners_api_v1_admin_carpets__carpet_id__ar_corners_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArCornerSuggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_ar_assets_api_v1_admin_carpets__carpet_id__ar_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ArGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_v1_admin_carpets__carpet_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_admin_carpets__carpet_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_variant_api_v1_admin_carpets__carpet_id__variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_v1_admin_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_image_api_v1_admin_images__image_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_admin_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_admin_orders_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["OrderStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_status_api_v1_admin_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_variant_api_v1_admin_variants__variant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_variant_api_v1_admin_variants__variant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: {
                farsh_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_carpets_api_v1_carpets_get: {
        parameters: {
            query?: {
                /** @description جست‌وجوی متنی */
                q?: string | null;
                /** @description چند مقدار، با تکرار همین پارامتر */
                pattern?: components["schemas"]["CarpetPattern"][] | null;
                /** @description چند مقدار، با تکرار همین پارامتر */
                material?: components["schemas"]["CarpetMaterial"][] | null;
                /** @description چند مقدار، با تکرار همین پارامتر */
                room?: components["schemas"]["RoomType"][] | null;
                /** @description چند مقدار، با تکرار همین پارامتر */
                id?: number[] | null;
                /** @description چند مقدار، با تکرار همین پارامتر */
                color?: components["schemas"]["ColorFamily"][] | null;
                min_width_cm?: number | null;
                max_width_cm?: number | null;
                min_length_cm?: number | null;
                max_length_cm?: number | null;
                min_price?: number | string | null;
                max_price?: number | string | null;
                sort?: "newest" | "price_asc" | "price_desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CarpetListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_facets_api_v1_carpets_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogFacets"];
                };
            };
        };
    };
    similar_carpets_api_v1_carpets__carpet_id__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                carpet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    carpet_detail_api_v1_carpets__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarpetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_order_api_v1_orders_track_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderTrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_adviser_api_v1_room_adviser_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_room_adviser_api_v1_room_adviser_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomAdviserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    size_guide_api_v1_room_size_guide_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_size_guide_api_v1_room_size_guide_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SizeGuideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversational_search_api_v1_search_conversational_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationalQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationalSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visual_search_api_v1_search_visual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_visual_search_api_v1_search_visual_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
