"""Initial schema: catalog (carpets, variants, images) and orders.

Written by hand rather than autogenerated so the vector/trgm extensions and
the HNSW index are explicit and reviewable.

Revision ID: 0001
Revises:
Create Date: 2026-07-28

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 768


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "carpets",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("slug", sa.String(120), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pattern", sa.String(30), nullable=False),
        sa.Column("material", sa.String(30), nullable=False),
        sa.Column("colors", postgresql.ARRAY(sa.String(7)), nullable=False),
        sa.Column("suitable_rooms", postgresql.ARRAY(sa.String(30)), nullable=False),
        sa.Column("origin", sa.String(100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_carpets_slug", "carpets", ["slug"], unique=True)
    op.create_index("ix_carpets_is_active", "carpets", ["is_active"])
    # trigram indexes make Persian substring search fast without a search engine
    op.execute(
        "CREATE INDEX ix_carpets_name_trgm ON carpets USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_carpets_description_trgm ON carpets "
        "USING gin (description gin_trgm_ops)"
    )

    op.create_table(
        "carpet_variants",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "carpet_id",
            sa.Integer(),
            sa.ForeignKey("carpets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("width_cm", sa.Integer(), nullable=False),
        sa.Column("length_cm", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(12, 0), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("glb_url", sa.String(500), nullable=True),
        sa.Column("usdz_url", sa.String(500), nullable=True),
        sa.Column("ar_status", sa.String(20), nullable=False, server_default="missing"),
        sa.Column("ar_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("carpet_id", "width_cm", "length_cm", name="uq_variant_size"),
        sa.CheckConstraint("width_cm > 0 AND length_cm > 0", name="ck_variant_positive_size"),
        sa.CheckConstraint("price >= 0", name="ck_variant_price_non_negative"),
    )
    op.create_index("ix_carpet_variants_carpet_id", "carpet_variants", ["carpet_id"])

    op.create_table(
        "carpet_images",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "carpet_id",
            sa.Integer(),
            sa.ForeignKey("carpets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("url", sa.String(500), nullable=False),
        sa.Column("rectified_url", sa.String(500), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_carpet_images_carpet_id", "carpet_images", ["carpet_id"])
    op.execute(
        "CREATE INDEX ix_carpet_images_embedding ON carpet_images "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("reference", sa.String(20), nullable=False),
        sa.Column("customer_name", sa.String(150), nullable=False),
        sa.Column("customer_phone", sa.String(20), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("total", sa.Numeric(12, 0), nullable=False, server_default="0"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_orders_reference", "orders", ["reference"], unique=True)
    op.create_index("ix_orders_status", "orders", ["status"])

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "order_id",
            sa.Integer(),
            sa.ForeignKey("orders.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "variant_id",
            sa.Integer(),
            sa.ForeignKey("carpet_variants.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("carpet_name", sa.String(200), nullable=False),
        sa.Column("width_cm", sa.Integer(), nullable=False),
        sa.Column("length_cm", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(12, 0), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("quantity > 0", name="ck_order_item_quantity_positive"),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"])


def downgrade() -> None:
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("carpet_images")
    op.drop_table("carpet_variants")
    op.drop_table("carpets")
